export const UI_COPY = {
  common: {
    retry: 'Tekrar Dene',
    residentsListAction: 'Sakin Listesi',
    paymentsPageAction: 'Ödemeler Sayfası',
    financePageAction: 'Tahsilat Sayfası',
  },
  finance: {
    title: 'Tahsilat',
    subtitle: 'Daire bazında borç durumu ve ödeme alma.',
    eyebrow: 'Finans Operasyonu',
    heroSubtitle: 'Daire bazında borç durumunu gör, ödeme al, hatırlat.',
    siteRequiredTitle: 'Tahsilat için site seçin',
    siteRequiredDescription: 'Daire bazlı borç ve tahsilat akışını görüntülemek için aktif bina seçimi zorunludur.',
    unauthorizedTitle: 'Yönetici Yetkisi Gerekli',
    unauthorizedDescription: 'Bu ekran yalnızca yönetici yetkisiyle kullanılabilir.',
  },
  payments: {
    title: 'Ödemeler',
    eyebrow: 'Finans Kayıtları',
    subtitle: 'Tahsil edilen ödemelerin tam listesi ve iade işlemleri.',
    siteRequiredTitle: 'Ödemeler için site seçin',
    siteRequiredDescription: 'Filtrelenmiş ödeme geçmişi, mutabakat ve şüpheli işlem listesi aktif site seçimiyle açılır.',
    loadErrorTitle: 'Ödeme verisi yüklenemedi',
    loadErrorDescription: 'Ödeme kayıtları alınamadı.',
  },
  dashboard: {
    title: 'Genel Bakış',
    eyebrow: 'Wafra Enterprise Console',
    selectedSiteSubtitleSuffix: 'için günlük durum özeti, tahsilat ritmi ve öncelikli operasyon aksiyonları tek yüzeyde.',
    portfolioSubtitle: 'Tüm portföyün günlük durum özeti, tahsilat ritmi ve öncelikli operasyon aksiyonları tek yüzeyde.',
    portfolioChip: 'Tüm Portföy',
    siteErrorTitle: 'Site verisi alınamadı',
    siteErrorAction: "Dashboard'a Dön",
    quickActions: {
      collection: 'Tahsilat',
      overdue: 'Gecikmiş Aidatlar',
      residents: 'Sakin İşlemleri',
    },
    actionCards: {
      overdueMessage: 'Gecikmiş aidatları tahsilat merkezinden tek akışta kapatın.',
      overdueCta: 'Tahsilata Git',
      overdueListMessage: 'Gecikmiş aidat listesine geçip öncelikli daireleri filtreleyin.',
      overdueListCta: 'Gecikmiş Aidatlar',
      residentMessage: 'Sakin kaydını açın, açık borç ve son ödeme geçmişini doğrulayın.',
      residentCta: 'Sakin İşlemleri',
    },
    sections: {
      portfolioRiskTitle: 'Portföy Risk Paneli',
      portfolioRiskSubtitle: 'Tahsilat seviyesi, açık borç ve bina riskini tek listede topla.',
      topDebtorsTitle: 'En Borçlu Daireler',
      topDebtorsSubtitle: 'Öncelikli tahsilat gerektiren daireleri en üstte tut.',
      topDebtorsEmpty: 'Açık borç kaydı bulunamadı.',
      operationsTitle: 'Operasyon Aksiyonları',
      operationsSubtitle: 'Tek tıkla kritik akışlara geçiş.',
      dayEndTitle: 'Gün Sonu Kontrolü',
      dayEndSubtitle: "Kapanış öncesi kısa operasyon checklist'i.",
      recentPaymentsTitle: 'Son Tahsilatlar',
      recentPaymentsSubtitle: 'Yakın zamanda kayda geçen ödemeleri hızlıca denetle.',
      recentPaymentsEmpty: 'Tahsilat kaydı yok.',
    },
    checklist: {
      step1Title: '1. Günlük tahsilat özeti doğrulandı',
      step1NotePrefix: 'Bugün onaylanan tahsilat:',
      step2Title: '2. Uyum ve risk kontrolü yapıldı',
      step2HighRiskPrefix: 'Yüksek riskli site:',
      step2OpenDebtPrefix: 'Açık borç işlemi:',
      step3Title: '3. Gecikmiş kayıtlar için yarın planı hazır',
      step3OverduePrefix: 'Gecikmiş kayıt:',
      step3OverdueDebtPrefix: 'Gecikmiş borç:',
    },
    collectButton: 'Tahsil Et',
    unknownResident: 'Bilinmeyen',
    unassignedResident: 'Sorumlu atanmamış',
  },
  paymentsPanel: {
    filtersTitle: 'Filtreleme',
    filtersSubtitle: 'Makbuz, yöntem ve durum filtresiyle tahsilat akışını daralt.',
    searchPlaceholder: 'Makbuz, not, daire no ara...',
    filterButton: 'Filtrele',
    clearButton: 'Temizle',
    refreshButton: 'Yenile',
    receiptReportButton: 'Makbuz Raporu',
    auditReportButton: 'Denetim Raporu',
    sectionTitle: 'Tahsilat Akışı',
    sectionSubtitleFallback: 'Filtreye uyan ödeme kayıtları ve durumları.',
    sectionSubtitleResultSuffix: 'kayıt bulundu.',
    emptyTitle: 'Ödeme bulunamadı',
    emptyDescription: 'Filtreye uygun ödeme kaydı yok.',
    suspiciousTitle: 'Şüpheli İşlemler',
    suspiciousSubtitle: 'İnceleme gerektiren tahsilat kayıtları.',
    suspiciousLoadError: 'Şüpheli işlem listesi alınamadı.',
    suspiciousEmptyTitle: 'Şüpheli ödeme yok',
    suspiciousEmptyDescription: 'Şu an inceleme gerektiren ödeme kaydı görünmüyor.',
  },
  duesRecords: {
    loadErrorTitle: 'Aidat kayıtları yüklenemedi',
    loadErrorDescription: 'Aidat kayıtları alınamadı.',
    summary: {
      totalLabel: 'Toplam Kayıt',
      totalHint: 'Seçili filtreye göre aidat satırları.',
      openBalanceLabel: 'Açık Bakiye',
      openBalanceHint: 'Ödenmemiş toplam borç miktarı.',
      overdueLabel: 'Gecikmiş',
      overdueHint: 'Vadesi geçmiş aidat adedi.',
    },
    filtersTitle: 'Filtreleme',
    filtersSubtitle: 'Daire no, dönem ve durum filtresiyle aidat kayıtlarını daraltın.',
    searchPlaceholder: 'Daire no, site adı, açıklama…',
    filterButton: 'Filtrele',
    clearButton: 'Temizle',
    sectionTitle: 'Aidat Kayıtları',
    sectionSubtitleFallback: 'Daire bazında dönem, tutar ve durum dağılımı.',
    sectionSubtitleResultSuffix: 'kayıt bulundu.',
    emptyTitle: 'Aidat kaydı bulunamadı',
    emptyDescription: 'Bu filtreyle eşleşen aidat yok — filtre ayarlarını değiştirin veya yeni dönem oluşturun.',
    collectButton: 'Tahsil',
    waiveButton: 'Affet',
    waiveConfirmButton: 'Onayla',
    waiveConfirmMobileButton: 'Affı Onayla',
    cancelButton: 'Vazgeç',
  },
  residents: {
    title: 'Sakinler',
    eyebrow: 'İletişim Operasyonu',
    pageSubtitle: 'Sakin kayıtlarını, bağlı daireleri ve toplu işlem akışlarını tek ekrandan yönetin.',
    siteRequiredSubtitle: 'Sakin kaydı, borç geçmişi ve iletişim akışı site seçimiyle filtrelenir.',
    fallbackSubtitle: 'Sakin kayıtlarını tek ekrandan yönetin.',
    siteRequiredTitle: 'Sakin listesi için site seçin',
    siteRequiredDescription: 'Doğru bina bağlamı olmadan sakin kayıtları ve borç geçmişi gösterilmez.',
    loadErrorTitle: 'Sakin verisi yüklenemedi',
    detailTitle: 'Sakin Detayı',
    detailSubtitle: 'Sakin kaydı ve ödeme geçmişi görünümü.',
    detailUnauthorizedSubtitle: 'Sakin detay ve borç geçmişine erişim için yetki gerekir.',
    detailUnauthorizedTitle: 'Sakin detay ekranı için yetki gerekli',
    detailUnauthorizedDescription: 'Bu ekranı görüntülemek için yetkiniz yok.',
    detailLoadErrorSubtitle: 'Sakin kaydı ve borç geçmişi görüntülenemedi.',
    detailLoadErrorTitle: 'Sakin detayı yüklenemedi',
    detailMissingTitle: 'Sakin kaydı bulunamadı',
    detailMissingSubtitle: 'Talep edilen sakin kaydı bu tenant bağlamında bulunamadı.',
    detailMissingDescription: 'Kayıt taşınmış olabilir veya mevcut site bağlamında erişim dışıdır.',
  },
} as const
